### ISSUE TITLE
Question: About Internationalization Directory Structure

### ISSUE THREAD

**Issue by k-kuwahara** [riot/next#2]
Hi, @GianlucaGuarini 

What about the directory structure for internationalization? 

I want to start Japanese translation early, so it would be helpful if you could tell me earlier.

thanks.

**Comment by GianlucaGuarini** [comment]
you can create a `/jp` folder in the root of the project. We can link to that folder. The same could be done for other languages as well. At moment it's missing a language switcher though. PRs are welcome

**Comment by k-kuwahara** [comment]
@GianlucaGuarini 
Thank you for your reply! OK, create a topic branch and create a `draft` PR. When all pages have been translated, I will go out in a flow of removing the draft.

**Comment by GianlucaGuarini** [comment]
You got the writing right on this repo. Remember that it will be moved here soon https://github.com/riot/riot.github.io afterwards

**Comment by k-kuwahara** [comment]
You're right, but in fact I'm not a member because I'm off....
